### ISSUE TITLE
Add comparison to other formats, specifically `Smile`

### ISSUE THREAD

**Issue by cowtowncoder** [EXIficient/exificient-for-json#4]
In addition to comparison to CBOR encoding, I think it'd be interesting to see how `Smile` performs.
While similar to CBOR in many ways it does include name/String back-references, similar to some of other binary-XML encoders.
Codec is available at https://github.com/FasterXML/jackson-dataformats-binary/.

**Comment by danielpeintner** [comment]
Adding Smile as another test candidate makes perfect sense and so I did add it to https://github.com/EXIficient/exificient-for-json#compression-results

**Comment by cowtowncoder** [comment]
Excellent, thank you!
